version: '3.8'

services:

# After starting the container, NATS with JetStream is now accessible at 
# nats://127.0.0.1:4222 for client connections and 
# http://127.0.0.1:8222 for monitoring.
  postgres:
    image: postgres:15
    container_name: dddforum-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dddforum
      POSTGRES_PASSWORD: dddforum
      POSTGRES_DB: dddforum
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: