name: Best Practices Assignment - Automatically Deploy to Staging and Production

on:
  workflow_run:
    workflows: ["Best Practices Assignment - Commit Phase"]
    types:
      - completed

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"