name: Best Practices Assignment - Automatically Deploy to Staging and Production

on:
  workflow_run:
    workflows: ["Best Practices Assignment - Commit Phase"]
    types:
      - completed

jobs:
  staging:
    name: Wait for Deploy to stage
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          service-id: srv-cpvcjehu0jms73apojq0
          retries: 20
          wait: 16000
          sleep: 30000
